
version: '1.0.{build}'
image: Visual Studio 2019
configuration: Release
# platform: Any CPU
nuget:
  project_feed: true
branches:
  only:
  - master
  - buchenberg/develop
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/Hangfire.Realm.sln --verbosity m
build:
  project: ./src/Hangfire.Realm.sln
  publish_nuget: true
clone_depth: 1
deploy:
  provider: NuGet
  api_key:
    secure: oy2klc57xnxiodydafdaevdv2e46jbnetfhi2jjt4tssly
  skip_symbols: false
  artifact: /.*\.nupkg/
